import sys
import os
import logging

# Configure logging to match main.py
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger("test_structure")

# Add src to path
sys.path.insert(0, os.path.join(os.getcwd(), 'src'))

try:
    from repo_mapper import RepoMapper
    
    logger.info("Initializing RepoMapper for current directory...")
    mapper = RepoMapper(os.getcwd())
    
    logger.info("Generating repository context map...")
    repo_map = mapper.generate_context_map()
    
    print("\n" + "="*80)
    print("REPOSITORY MAP (Generated by RepoMapper)")
    print("="*80)
    print(repo_map)
    print("="*80)
    
    logger.info("Structure test completed successfully.")
    
except Exception as e:
    logger.error(f"Test failed: {e}", exc_info=True)
